package com.example.taskmanager;

import com.example.taskmanager.dto.TaskRequest;
import com.example.taskmanager.dto.TaskResponse;
import com.example.taskmanager.exception.ResourceNotFoundException;
import com.example.taskmanager.model.Task;
import com.example.taskmanager.repository.TaskRepository;
import com.example.taskmanager.service.TaskService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * TaskServiceTest — Unit Tests for TaskService
 *
 * Strategy:
 *   - We use Mockito to MOCK the TaskRepository
 *   - This means no real database is used
 *   - We test only the SERVICE logic in isolation
 *
 * Key annotations:
 *   @ExtendWith(MockitoExtension.class) → activates Mockito
 *   @Mock → creates a fake repository
 *   @InjectMocks → creates real TaskService and injects the mock repo
 */
@ExtendWith(MockitoExtension.class)
class TaskServiceTest {

    @Mock
    private TaskRepository taskRepository;

    @InjectMocks
    private TaskService taskService;

    private Task sampleTask;

    @BeforeEach
    void setUp() {
        // A reusable task object to return from mocked repository calls
        sampleTask = new Task("Test Task", "Test Description");
        // Use reflection-style to set id (since it's normally auto-generated by JPA)
        try {
            var field = Task.class.getDeclaredField("id");
            field.setAccessible(true);
            field.set(sampleTask, 1L);

            var createdAtField = Task.class.getDeclaredField("createdAt");
            createdAtField.setAccessible(true);
            createdAtField.set(sampleTask, LocalDateTime.now());

            var updatedAtField = Task.class.getDeclaredField("updatedAt");
            updatedAtField.setAccessible(true);
            updatedAtField.set(sampleTask, LocalDateTime.now());
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    // ─── CREATE TESTS ───────────────────────────────────

    @Test
    @DisplayName("Should create a task and return TaskResponse")
    void createTask_Success() {
        when(taskRepository.save(any(Task.class))).thenReturn(sampleTask);

        TaskRequest request = new TaskRequest("Test Task", "Test Description");
        TaskResponse response = taskService.createTask(request);

        assertThat(response).isNotNull();
        assertThat(response.getTitle()).isEqualTo("Test Task");
        assertThat(response.getStatus()).isEqualTo("OPEN");

        verify(taskRepository, times(1)).save(any(Task.class));
    }

    @Test
    @DisplayName("New task should have OPEN status")
    void createTask_ShouldHaveOpenStatus() {
        when(taskRepository.save(any(Task.class))).thenReturn(sampleTask);

        TaskRequest request = new TaskRequest("My Task", null);
        TaskResponse response = taskService.createTask(request);

        assertThat(response.getStatus()).isEqualTo("OPEN");
    }

    // ─── GET ALL TESTS ──────────────────────────────────

    @Test
    @DisplayName("Should return all tasks as list of TaskResponse")
    void getAllTasks_ReturnsList() {
        when(taskRepository.findAll()).thenReturn(List.of(sampleTask));

        List<TaskResponse> result = taskService.getAllTasks();

        assertThat(result).hasSize(1);
        assertThat(result.get(0).getTitle()).isEqualTo("Test Task");
    }

    @Test
    @DisplayName("Should return empty list when no tasks exist")
    void getAllTasks_ReturnsEmptyList() {
        when(taskRepository.findAll()).thenReturn(List.of());

        List<TaskResponse> result = taskService.getAllTasks();

        assertThat(result).isEmpty();
    }

    // ─── GET BY ID TESTS ────────────────────────────────

    @Test
    @DisplayName("Should return task when valid ID provided")
    void getTaskById_Success() {
        when(taskRepository.findById(1L)).thenReturn(Optional.of(sampleTask));

        TaskResponse response = taskService.getTaskById(1L);

        assertThat(response).isNotNull();
        assertThat(response.getId()).isEqualTo(1L);
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException for unknown ID")
    void getTaskById_NotFound() {
        when(taskRepository.findById(99L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> taskService.getTaskById(99L))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("99");
    }

    // ─── UPDATE TESTS ───────────────────────────────────

    @Test
    @DisplayName("Should update task title and description")
    void updateTask_Success() {
        when(taskRepository.findById(1L)).thenReturn(Optional.of(sampleTask));
        when(taskRepository.save(any(Task.class))).thenReturn(sampleTask);

        TaskRequest updateRequest = new TaskRequest("Updated Title", "Updated Description");
        TaskResponse response = taskService.updateTask(1L, updateRequest);

        assertThat(response).isNotNull();
        verify(taskRepository).save(any(Task.class));
    }

    @Test
    @DisplayName("Should throw exception when updating non-existent task")
    void updateTask_NotFound() {
        when(taskRepository.findById(99L)).thenReturn(Optional.empty());

        TaskRequest request = new TaskRequest("Title", "Desc");
        assertThatThrownBy(() -> taskService.updateTask(99L, request))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    // ─── DELETE TESTS ───────────────────────────────────

    @Test
    @DisplayName("Should delete task when valid ID provided")
    void deleteTask_Success() {
        when(taskRepository.existsById(1L)).thenReturn(true);
        doNothing().when(taskRepository).deleteById(1L);

        assertThatCode(() -> taskService.deleteTask(1L)).doesNotThrowAnyException();

        verify(taskRepository).deleteById(1L);
    }

    @Test
    @DisplayName("Should throw exception when deleting non-existent task")
    void deleteTask_NotFound() {
        when(taskRepository.existsById(99L)).thenReturn(false);

        assertThatThrownBy(() -> taskService.deleteTask(99L))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    // ─── MARK COMPLETE TESTS ────────────────────────────

    @Test
    @DisplayName("Should mark task as DONE")
    void markTaskComplete_Success() {
        when(taskRepository.findById(1L)).thenReturn(Optional.of(sampleTask));
        when(taskRepository.save(any(Task.class))).thenAnswer(inv -> {
            Task t = inv.getArgument(0);
            t.setStatus(Task.TaskStatus.DONE);
            return t;
        });

        TaskResponse response = taskService.markTaskComplete(1L);

        assertThat(response.getStatus()).isEqualTo("DONE");
    }

    @Test
    @DisplayName("Should throw exception when completing non-existent task")
    void markTaskComplete_NotFound() {
        when(taskRepository.findById(999L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> taskService.markTaskComplete(999L))
                .isInstanceOf(ResourceNotFoundException.class);
    }
}
